### ISSUE TITLE
tab instead of four spaces in readme

### ISSUE THREAD

**Issue by 030** [andrewrothstein/ansible-atom#8]
```yml
- hosts: servers
  roles:
	- andrewrothstein.atom
```

should be

```yml
- hosts: servers
  roles:
    - andrewrothstein.atom
```
